server:
  port: 8080

mybatis:
  mapper-locations: classpath:mapping/*.xml

spring:
  datasource:
    name: miaosha
    url: jdbc:mysql://localhost:3306/miaosha?useSSL=false&useUnicode=true&characterEncoding=utf8
    username: root
    password: 123456
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: com.mysql.jdbc.Driver